name: List Files in Repository

on: [push]

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all files
        run: |
          echo "Listing all files in the repository:"
          ls -R
      - name: cloning the another repository 
        run: |
          git clone https://github.com/mohantest14242/java_testing.git 

      - name: listing the all testcases and sorurce code1
        run: |
          ls 
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
