name: List Files in Repository

on: [push]

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List all files
        run: |
          echo "Listing all files in the repository:"
          ls -R
